services:
  mcpd:
    build:
      context: .
    container_name: mcpd
    environment:
      MCPD_API_PORT: ${MCPD_API_PORT:-8090}
      MCPD_LOG_LEVEL: ${MCPD_LOG_LEVEL:-INFO}
      MCPD_LOG_PATH: ${MCPD_LOG_PATH:-/var/log/mcpd/mcpd.log}
      MCPD_CONFIG_FILE: ${MCPD_CONFIG_FILE:-/etc/mcpd/.mcpd.toml}
      MCPD_RUNTIME_FILE: ${MCPD_RUNTIME_FILE:-/home/mcpd/.config/mcpd/secrets.prd.toml}
    ports:
      - "${MCPD_API_PORT:-8090}:${MCPD_API_PORT:-8090}"
    volumes:
      - "${HOME}/.config/mcpd/secrets.dev.toml:/home/mcpd/.config/mcpd/secrets.prd.toml:ro"
      - "./.mcpd.toml:/etc/mcpd/.mcpd.toml:ro"
      - "./mcpd-container-logs:/var/log/mcpd"