site_name: mcpd documentation
site_url: https://mozilla-ai.github.io/mcpd/
repo_name: mozilla-ai/mcpd
repo_url: https://github.com/mozilla-ai/mcpd
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: grey
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: grey
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font:
    text: Roboto
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.sections
    - toc.integrate
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - Home: index.md
  - Requirements: requirements.md
  - Configuration: configuration.md
  - CLI Reference:
      - Overview: commands/mcpd.md
      - add: commands/mcpd_add.md
      - config: commands/mcpd_config.md
      - config set-args: commands/mcpd_config_set-args.md
      - config set-env: commands/mcpd_config_set-env.md
      - daemon: commands/mcpd_daemon.md
      - init: commands/mcpd_init.md
      - remove: commands/mcpd_remove.md
      - search: commands/mcpd_search.md
  - Execution Context: execution-context.md
  - Makefile: makefile.md
  - Tutorial: tutorial.md
