blank_issues_enabled: false
contact_links:
  - name: Report a security vulnerability
    url: https://github.com/mozilla-ai/mcpd/security/policy
    about: Please report security vulnerabilities responsibly.