blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/mozilla-ai/mcpd/discussions/new?category=q-a
    about: Ask a question about the project or how to use it.
  - name: Report a security vulnerability
    url: https://github.com/mozilla-ai/mcpd/security/policy
    about: Please report security vulnerabilities responsibly.