name: Release Binary

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      skip_publish:
        description: "Skip binary publish"
        required: false
        default: "false"
      skip_announce:
        description: "Skip announce"
        required: false
        default: "false"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Go (from go.mod)
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@9c156ee8a17a598857849441385a2041ef570552 # v6.3.0
        with:
          distribution: goreleaser
          version: latest
          args: >
            release --clean
            ${{ github.event.inputs.skip_publish == 'true' && ' --skip-publish' || '' }}
            ${{ github.event.inputs.skip_announce == 'true' && ' --skip-announce' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}